### ISSUE TITLE
Getting email about query completion but query gets submitted again

### ISSUE THREAD

**Issue by vik-y** [zense/stalkerGKSU#8]
In production : When I create a query with the organisation id and email, I do get a confirmation email regarding query completion but when I resubmit the same query I don't get any results. In fact, it creates a new query again. I think it has something to do with Issue #7 

worker.py logs 
```
worker_1   | 21:18:22 RQ worker u'rq:worker:2551067be3a5.1' started, version 0.9.2
worker_1   | 21:18:22 Cleaning registries for queue: default
worker_1   | 21:18:22 
worker_1   | 21:18:22 *** Listening on default...
worker_1   | 21:18:38 default: routes.save_info(u'iiitb', u'vikas.yadav@iiitb.org') (877027e2-3b9a-4b8f-af2a-a9bf238d81a2)
worker_1   | 21:22:53 Warm shut down requested
worker_1   | 08:05:13 RQ worker u'rq:worker:2551067be3a5.1' started, version 0.9.2
worker_1   | 08:05:13 Cleaning registries for queue: default
worker_1   | 08:05:13 
worker_1   | 08:05:13 *** Listening on default...
worker_1   | 08:05:35 default: main.save_info(u'iiitb', u'vikas.yadav@iiitb.org') (fc214993-6b06-4db6-8cb8-266a0a70a95d)
worker_1   | send: 'ehlo [172.17.0.6]\r\n'
worker_1   | reply: '250-email-smtp.amazonaws.com\r\n'
worker_1   | reply: '250-8BITMIME\r\n'
worker_1   | reply: '250-SIZE 10485760\r\n'
worker_1   | reply: '250-AUTH PLAIN LOGIN\r\n'
worker_1   | reply: '250 Ok\r\n'
worker_1   | reply: retcode (250); Msg: email-smtp.amazonaws.com
worker_1   | 8BITMIME
worker_1   | SIZE 10485760
worker_1   | AUTH PLAIN LOGIN
worker_1   | Ok
worker_1   | send: 'AUTH PLAIN AEFLSUFJT1VZWTRHQVFVWlVDM1FRAEF2ZDJNaHRmN0FmSVUzNUVpSExzc2JhM3VhZ2lyVXgyelBHQVV4V3MrbGk0\r\n'
worker_1   | reply: '235 Authentication successful.\r\n'
worker_1   | reply: retcode (235); Msg: Authentication successful.
worker_1   | send: u'mail FROM:<noreply@zense.co.in> size=496\r\n'
worker_1   | reply: '250 Ok\r\n'
worker_1   | reply: retcode (250); Msg: Ok
worker_1   | send: u'rcpt TO:<vikas.yadav@iiitb.org>\r\n'
worker_1   | reply: '250 Ok\r\n'
worker_1   | reply: retcode (250); Msg: Ok
worker_1   | send: 'data\r\n'
worker_1   | reply: '354 End data with <CR><LF>.<CR><LF>\r\n'
worker_1   | reply: retcode (354); Msg: End data with <CR><LF>.<CR><LF>
worker_1   | data: (354, 'End data with <CR><LF>.<CR><LF>')
worker_1   | send: 'Content-Type: text/plain; charset="utf-8"\r\nMIME-Version: 1.0\r\nContent-Transfer-Encoding: 7bit\r\nSubject: Results have been generated for iiitb\r\nFrom: noreply@zense.co.in\r\nTo: vikas.yadav@iiitb.org\r\nDate: Sun, 17 Dec 2017 08:05:50 +0000\r\nMessage-ID: <151349794223.8.12601765427137254689@2551067be3a5>\r\n\r\n Greetings from Zense,\r\n\r\n                    We have completed your task in regards to iiitb\r\n                    Please visit us back\r\n\r\n                    Regards,\r\n                    Team Stalker, Zense \r\n.\r\n'
worker_1   | reply: '250 Ok 01000160638206d8-9245f032-3332-45c9-a525-70547aebc9fe-000000\r\n'
worker_1   | reply: retcode (250); Msg: Ok 01000160638206d8-9245f032-3332-45c9-a525-70547aebc9fe-000000
worker_1   | data: (250, 'Ok 01000160638206d8-9245f032-3332-45c9-a525-70547aebc9fe-000000')
worker_1   | send: 'quit\r\n'
worker_1   | reply: '221 Bye\r\n'
worker_1   | reply: retcode (221); Msg: Bye
worker_1   | 08:05:53 default: Job OK (fc214993-6b06-4db6-8cb8-266a0a70a95d)
worker_1   | 08:05:53 Result is kept for 5000 seconds
worker_1   | 08:05:53 
worker_1   | 08:05:53 *** Listening on default...
worker_1   | 08:05:53 default: main.save_info(u'iiitb', u'') (fa9abd48-2145-4a9e-b860-157beea46559)
worker_1   | send: 'ehlo [172.17.0.6]\r\n'
worker_1   | reply: '250-email-smtp.amazonaws.com\r\n'
worker_1   | reply: '250-8BITMIME\r\n'
worker_1   | reply: '250-SIZE 10485760\r\n'
worker_1   | reply: '250-AUTH PLAIN LOGIN\r\n'
worker_1   | reply: '250 Ok\r\n'
worker_1   | reply: retcode (250); Msg: email-smtp.amazonaws.com
worker_1   | 8BITMIME
worker_1   | SIZE 10485760
worker_1   | AUTH PLAIN LOGIN
worker_1   | Ok
worker_1   | send: 'AUTH PLAIN AEFLSUFJT1VZWTRHQVFVWlVDM1FRAEF2ZDJNaHRmN0FmSVUzNUVpSExzc2JhM3VhZ2lyVXgyelBHQVV4V3MrbGk0\r\n'
worker_1   | reply: '235 Authentication successful.\r\n'
worker_1   | reply: retcode (235); Msg: Authentication successful.
worker_1   | send: u'mail FROM:<noreply@zense.co.in> size=475\r\n'
worker_1   | reply: '250 Ok\r\n'
worker_1   | reply: retcode (250); Msg: Ok
worker_1   | send: 'rcpt TO:<>\r\n'
worker_1   | reply: '501 Invalid RCPT TO address provided\r\n'
worker_1   | reply: retcode (501); Msg: Invalid RCPT TO address provided
worker_1   | send: 'rset\r\n'
worker_1   | reply: '250 Ok\r\n'
worker_1   | reply: retcode (250); Msg: Ok
worker_1   | send: 'quit\r\n'
worker_1   | reply: '221 Bye\r\n'
worker_1   | reply: retcode (221); Msg: Bye
worker_1   | 08:06:11 SMTPRecipientsRefused: {'': (501, 'Invalid RCPT TO address provided')}
worker_1   | Traceback (most recent call last):
worker_1   |   File "/usr/local/lib/python2.7/site-packages/rq/worker.py", line 771, in perform_job
worker_1   |     rv = job.perform()
worker_1   |   File "/usr/local/lib/python2.7/site-packages/rq/job.py", line 558, in perform
worker_1   |     self._result = self._execute()
worker_1   |   File "/usr/local/lib/python2.7/site-packages/rq/job.py", line 564, in _execute
worker_1   |     return self.func(*self.args, **self.kwargs)
worker_1   |   File "/app/main.py", line 38, in save_info
worker_1   |     emails.send_email(organisation, [email_address])
worker_1   |   File "/app/emails.py", line 19, in send_email
worker_1   |     mail.send(msg)
worker_1   |   File "/usr/local/lib/python2.7/site-packages/flask_mail.py", line 492, in send
worker_1   |     message.send(connection)
worker_1   |   File "/usr/local/lib/python2.7/site-packages/flask_mail.py", line 427, in send
worker_1   |     connection.send(self)
worker_1   |   File "/usr/local/lib/python2.7/site-packages/flask_mail.py", line 192, in send
worker_1   |     message.rcpt_options)
worker_1   |   File "/usr/local/lib/python2.7/smtplib.py", line 747, in sendmail
worker_1   |     raise SMTPRecipientsRefused(senderrs)
worker_1   | SMTPRecipientsRefused: {'': (501, 'Invalid RCPT TO address provided')}
worker_1   | Traceback (most recent call last):
worker_1   |   File "/usr/local/lib/python2.7/site-packages/rq/worker.py", line 771, in perform_job
worker_1   |     rv = job.perform()
worker_1   |   File "/usr/local/lib/python2.7/site-packages/rq/job.py", line 558, in perform
worker_1   |     self._result = self._execute()
worker_1   |   File "/usr/local/lib/python2.7/site-packages/rq/job.py", line 564, in _execute
worker_1   |     return self.func(*self.args, **self.kwargs)
worker_1   |   File "/app/main.py", line 38, in save_info
worker_1   |     emails.send_email(organisation, [email_address])
worker_1   |   File "/app/emails.py", line 19, in send_email
worker_1   |     mail.send(msg)
worker_1   |   File "/usr/local/lib/python2.7/site-packages/flask_mail.py", line 492, in send
worker_1   |     message.send(connection)
worker_1   |   File "/usr/local/lib/python2.7/site-packages/flask_mail.py", line 427, in send
worker_1   |     connection.send(self)
worker_1   |   File "/usr/local/lib/python2.7/site-packages/flask_mail.py", line 192, in send
worker_1   |     message.rcpt_options)
worker_1   |   File "/usr/local/lib/python2.7/smtplib.py", line 747, in sendmail
worker_1   |     raise SMTPRecipientsRefused(senderrs)
worker_1   | SMTPRecipientsRefused: {'': (501, 'Invalid RCPT TO address provided')}
worker_1   | 08:06:11 Moving job to u'failed' queue
worker_1   | 08:06:11 
worker_1   | 08:06:11 *** Listening on default...
worker_1   | 08:06:11 default: main.save_info(u'iiitb', u'vikas.yadav@iiitb.org') (bb69746e-f9fc-48ea-9ebd-a041540a4f2b)
worker_1   | send: 'ehlo [172.17.0.6]\r\n'
worker_1   | reply: '250-email-smtp.amazonaws.com\r\n'
worker_1   | reply: '250-8BITMIME\r\n'
worker_1   | reply: '250-SIZE 10485760\r\n'
worker_1   | reply: '250-AUTH PLAIN LOGIN\r\n'
worker_1   | reply: '250 Ok\r\n'
worker_1   | reply: retcode (250); Msg: email-smtp.amazonaws.com
worker_1   | 8BITMIME
worker_1   | SIZE 10485760
worker_1   | AUTH PLAIN LOGIN
worker_1   | Ok
worker_1   | send: 'AUTH PLAIN AEFLSUFJT1VZWTRHQVFVWlVDM1FRAEF2ZDJNaHRmN0FmSVUzNUVpSExzc2JhM3VhZ2lyVXgyelBHQVV4V3MrbGk0\r\n'
worker_1   | reply: '235 Authentication successful.\r\n'
worker_1   | reply: retcode (235); Msg: Authentication successful.
worker_1   | send: u'mail FROM:<noreply@zense.co.in> size=496\r\n'
worker_1   | reply: '250 Ok\r\n'
worker_1   | reply: retcode (250); Msg: Ok
worker_1   | send: u'rcpt TO:<vikas.yadav@iiitb.org>\r\n'
worker_1   | reply: '250 Ok\r\n'
worker_1   | reply: retcode (250); Msg: Ok
worker_1   | send: 'data\r\n'
worker_1   | reply: '354 End data with <CR><LF>.<CR><LF>\r\n'
worker_1   | reply: retcode (354); Msg: End data with <CR><LF>.<CR><LF>
worker_1   | data: (354, 'End data with <CR><LF>.<CR><LF>')
worker_1   | send: 'Content-Type: text/plain; charset="utf-8"\r\nMIME-Version: 1.0\r\nContent-Transfer-Encoding: 7bit\r\nSubject: Results have been generated for iiitb\r\nFrom: noreply@zense.co.in\r\nTo: vikas.yadav@iiitb.org\r\nDate: Sun, 17 Dec 2017 08:06:26 +0000\r\nMessage-ID: <151349797886.12.4880812578895233536@2551067be3a5>\r\n\r\n Greetings from Zense,\r\n\r\n                    We have completed your task in regards to iiitb\r\n                    Please visit us back\r\n\r\n                    Regards,\r\n                    Team Stalker, Zense \r\n.\r\n'
worker_1   | reply: '250 Ok 0100016063829019-e2e70a1f-8c29-4e1a-a773-ec29f1ffd729-000000\r\n'
worker_1   | reply: retcode (250); Msg: Ok 0100016063829019-e2e70a1f-8c29-4e1a-a773-ec29f1ffd729-000000
worker_1   | data: (250, 'Ok 0100016063829019-e2e70a1f-8c29-4e1a-a773-ec29f1ffd729-000000')
worker_1   | send: 'quit\r\n'
worker_1   | reply: '221 Bye\r\n'
worker_1   | reply: retcode (221); Msg: Bye
worker_1   | 08:06:28 default: Job OK (bb69746e-f9fc-48ea-9ebd-a041540a4f2b)
worker_1   | 08:06:28 Result is kept for 5000 seconds
worker_1   | 08:06:28 
worker_1   | 08:06:28 *** Listening on default...
worker_1   | 08:06:45 default: main.save_info(u'iiitb', u'vikas.yadav@iiitb.org') (91bf1954-71b7-4f92-96b3-4529c28bff45)
worker_1   | send: 'ehlo [172.17.0.6]\r\n'
worker_1   | reply: '250-email-smtp.amazonaws.com\r\n'
worker_1   | reply: '250-8BITMIME\r\n'
worker_1   | reply: '250-SIZE 10485760\r\n'
worker_1   | reply: '250-AUTH PLAIN LOGIN\r\n'
worker_1   | reply: '250 Ok\r\n'
worker_1   | reply: retcode (250); Msg: email-smtp.amazonaws.com
worker_1   | 8BITMIME
worker_1   | SIZE 10485760
worker_1   | AUTH PLAIN LOGIN
worker_1   | Ok
worker_1   | send: 'AUTH PLAIN AEFLSUFJT1VZWTRHQVFVWlVDM1FRAEF2ZDJNaHRmN0FmSVUzNUVpSExzc2JhM3VhZ2lyVXgyelBHQVV4V3MrbGk0\r\n'
worker_1   | reply: '235 Authentication successful.\r\n'
worker_1   | reply: retcode (235); Msg: Authentication successful.
worker_1   | send: u'mail FROM:<noreply@zense.co.in> size=497\r\n'
worker_1   | reply: '250 Ok\r\n'
worker_1   | reply: retcode (250); Msg: Ok
worker_1   | send: u'rcpt TO:<vikas.yadav@iiitb.org>\r\n'
worker_1   | reply: '250 Ok\r\n'
worker_1   | reply: retcode (250); Msg: Ok
worker_1   | send: 'data\r\n'
worker_1   | reply: '354 End data with <CR><LF>.<CR><LF>\r\n'
worker_1   | reply: retcode (354); Msg: End data with <CR><LF>.<CR><LF>
worker_1   | data: (354, 'End data with <CR><LF>.<CR><LF>')
worker_1   | send: 'Content-Type: text/plain; charset="utf-8"\r\nMIME-Version: 1.0\r\nContent-Transfer-Encoding: 7bit\r\nSubject: Results have been generated for iiitb\r\nFrom: noreply@zense.co.in\r\nTo: vikas.yadav@iiitb.org\r\nDate: Sun, 17 Dec 2017 08:07:01 +0000\r\nMessage-ID: <151349801347.14.12290865206134913933@2551067be3a5>\r\n\r\n Greetings from Zense,\r\n\r\n                    We have completed your task in regards to iiitb\r\n                    Please visit us back\r\n\r\n                    Regards,\r\n                    Team Stalker, Zense \r\n.\r\n'
worker_1   | reply: '250 Ok 0100016063831c52-8be64b0a-e3e3-49f9-a2b9-9b392a54bd93-000000\r\n'
worker_1   | reply: retcode (250); Msg: Ok 0100016063831c52-8be64b0a-e3e3-49f9-a2b9-9b392a54bd93-000000
worker_1   | data: (250, 'Ok 0100016063831c52-8be64b0a-e3e3-49f9-a2b9-9b392a54bd93-000000')
worker_1   | send: 'quit\r\n'
worker_1   | reply: '221 Bye\r\n'
worker_1   | reply: retcode (221); Msg: Bye
worker_1   | 08:07:04 default: Job OK (91bf1954-71b7-4f92-96b3-4529c28bff45)
worker_1   | 08:07:04 Result is kept for 5000 seconds
worker_1   | 08:07:04 
worker_1   | 08:07:04 *** Listening on default...
```

**Comment by gopuvenkat** [comment]
The organisation `iiitb` has no members. So there no members to be stored in the table. Hence we don't have the cached information corresponding to such organisations.
Since we don't have the cached information corresponding to such organisations we try to get the information from Github. Hence an email is always sent. We should cache that there aren't people associated with such organisations.

If we rather try `zense` or `iiitb2014` (for the second time), the cached results will be instantly displayed.

**Comment by vik-y** [comment]
Well zense and iiitb2014 are working for me as well. But then again if I try something else it doesn't work. For example try `amahi` and see if it works for you.

**Comment by vik-y** [comment]
Dropped the db and started things from scratch. Looks like it is working fine now.
